version: "3.9"
services:
  discountservice-api:
    build: .
    image: canberkt/discountservice-4app:0.0.1
    container_name: DiscountService
    restart: always
    ports:
      - 8081:8080
    environment:
      SPRING_DATA_MONGODB_HOST: discountservice-mongodb
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: Ab123456
      SPRING_DATA_MONGODB_DATABASE: DiscountService
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_MONGODB_PORT: 27017
    depends_on:
      discountservice-mongodb:
        condition: service_healthy

  discountservice-mongodb:
    image: mongo:4.4.28
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Ab123456
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_PORT: 27017
    ports:
      - "27018:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand(\"ping\").ok' --username root --password Ab123456 --authenticationDatabase admin --quiet"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8051:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Ab123456
      ME_CONFIG_MONGODB_URL: mongodb://root:Ab123456@discountservice-mongodb:27017/DiscountService?authSource=admin
      ME_CONFIG_BASICAUTH: false
    depends_on:
      discountservice-mongodb:
        condition: service_healthy